version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: "public.ecr.aws/o2v6d8f8/demoecrr"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y aws-cli docker

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - echo "Tagging the Docker image..."
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo "Build and push completed successfully."

artifacts:
  files:
    - '**/*'

