version: 0.2

env:
  variables:
    REPOSITORY_NAME: my-docker-repo
    ECR_REGISTRY: 022499006293.dkr.ecr.us-east-1.amazonaws.com

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Dependencies installed."
      
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --region us-east-1 ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - echo "Logging in complete."
      
  build:
    commands:
      - echo "Calculating source hash..."
      - SRC_HASH=`echo $CODEBUILD_SOURCE_VERSION | awk -F'/' '{print $NF}' | awk -F'.zip' '{print $1}'`
      - echo Source code hash - $SRC_HASH
      - echo "Building Docker image..."
      -  docker build -f .Dockerfile -t $REPOSITORY_NAME:$SRC_HASH .
      - echo "Docker image built."

  post_build:
    commands:
      - echo "Tagging Docker image with SRC_HASH and latest..."
      - docker tag $REPOSITORY_NAME:$SRC_HASH 022499006293.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:$SRC_HASH
      - IMAGE_PATH= `echo 022499006293.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:$SRC_HASH`
      - echo "Pushing Docker image to ECR..."
      - docker PUSH $IMAGE_PATH
      - echo "Docker images pushed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: dist
