version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install # This step will ensure any future dependencies are installed
      - echo Dependencies installed.
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --region us-east-1 ecr get-login-password | docker login --username AWS --password-stdin 022499006293.dkr.ecr.us-east-1.amazonaws.com
      - echo Logging in complete.
      
  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${RepositoryName} .
      - echo Docker image built.

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag ${RepositoryName}:latest 022499006293.dkr.ecr.us-east-1.amazonaws.com/${RepositoryName}:latest
      - echo Pushing Docker image to ECR...
      - docker push 022499006293.dkr.ecr.us-east-1.amazonaws.com/${RepositoryName}:latest
      - echo Docker image pushed.

artifacts:
  files:
    - '**/*'
  base-directory: dist
